# Generated by Django 4.0.2 on 2022-03-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
